#!/usr/bin/perl

use strict;
use warnings;
#use JSON;
#use Data::Dumper;
use Digest::SHA1 qw( sha1 sha1_hex );


#local $/;
#open INFILE, "<", "bernds-hosts.json";
#my $json_text = <INFILE>;
#my $json_data = decode_json( $json_text );

#print Dumper( $json_data );

#my $hosts = $json_data->{'config'}->{'hosts'};
#print Dumper( $hosts );



my %configs;

open INFILE, "<", "bernds-hosts.csv";

while ( my $line = <INFILE> ) {

    chomp $line;
    #print "$line\n";

    # 'Host Name';'Alias/Description';'Display Name';'Address';'Address6';'Parent Hosts';'Max. Check Attempts';'Check Interval';...
    my @fields = split /;/, $line;
    $fields[31] = "'Notes ersetzt*'";

    my $host           = $fields[0];
    my $restofconfig   = join ";", @fields[6..40];

    next if $host eq "'Host Name'";  # Header line

    my $sha1 = sha1_hex( $restofconfig );
    #print $host;
    #print $restofconfig;

    $configs{ $sha1 }{ "count" }++;
    $configs{ $sha1 }{ "config" } = $restofconfig;
    push @{ $configs{ $sha1 }{ "hosts" } }, $host;

}


print "\n\n---------------------\n\n";
foreach my $key ( sort keys %configs ) {
    my $config = $configs{ $key }{ "config" };
    print "Config: $config\n";
    print "Used by: ";
    print $configs{ $key }{ "count" };
    print " hosts\n";
    print "Hosts: ";
    print join( ", ", @{ $configs{ $key }{ "hosts" } } );
    print "\n";
    print "\n";
}
print "---------------------\n";
